using Assistant.Api;
using Assistant.Api.Interface;
using Assistant.ServiceDefaults;
using Microsoft.AspNetCore.Mvc;
using OpenAI.Chat;

var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.Configure<OpenAiSettings>(builder.Configuration.GetSection(OpenAiSettings.SectionName));
builder.Services.AddSingleton<OpenAiClientFactory>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
    {
        var forecast = Enumerable.Range(1, 5).Select(index =>
                new WeatherForecast
                (
                    DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                    Random.Shared.Next(-20, 55),
                    summaries[Random.Shared.Next(summaries.Length)]
                ))
            .ToArray();
        return forecast;
    })
    .WithName("GetWeatherForecast")
    .WithOpenApi();

app.MapPost("/ping", ([FromBody] PingRequest request) => new PingResponse($"Pong: {request.Message}"));

app.MapPost("/complete", async ([FromBody] CompleteRequest request, OpenAiClientFactory clientFactory) =>
{
    var chatClient = clientFactory.GetChatClient();
    ChatMessage[] messages =
    [
        new SystemChatMessage("You are a helpful assistant, completing chat queries. Include the footnote \"Generated by Assistant API\" at the end of every message with a newline between the content and the footnote"),
        new UserChatMessage(request.Query)
    ];
    var response = await chatClient.CompleteChatAsync(messages);
    return new CompleteResponse(response.Value.Content.Last().Text);
});

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
